export const ROUTES = {
    LOGIN: '/login',
    DASHBOARD: '/',
    BRANCHES: '/branches',
    BRANCH_LIST: '/branches/list',
    BRANCH_GROUPS: '/branches/groups',
    DEVICES: '/devices',
    CALLLOGS: '/calllogs',
    CALLLOG_DETAILS: '/calllogs/details',
    ANALYTICS: '/analytics',
    EXPORTS: '/exports',
    MONITORING: '/monitoring',
    USERS: '/users',
    USERS_LOGIN_HISTORY: '/users/login-history',
    CONTACTS: '/contacts',
    LEAD_MANAGEMENT: '/lead-management',
    LEAD_MANAGEMENT_LIST: '/lead-management/list',
    DOUBLETICK: '/doubletick',
    DOUBLETICK_CONVERSATIONS: '/doubletick/conversations',
    DOUBLETICK_LEADS: '/doubletick/leads',
    DOUBLETICK_AREAS: '/doubletick/areas',
    DOUBLETICK_AREA_MAP: '/doubletick/area-map',
    NOTIFICATIONS: '/notifications',
};

