export const ROUTES = {
    LOGIN: '/login',
    DASHBOARD: '/',
    BRANCHES: '/branches',
    BRANCH_LIST: '/branches/list',
    BRANCH_GROUPS: '/branches/groups',
    DEVICES: '/devices',
    CALLLOGS: '/calllogs',
    CALLLOG_DETAILS: '/calllogs/details',
    ANALYTICS: '/analytics',
    EXPORTS: '/exports',
    MONITORING: '/monitoring',
    USERS: '/users',
    USERS_LOGIN_HISTORY: '/users/login-history',
    CONTACTS: '/contacts',
    LEAD_MANAGEMENT: '/lead-management',
    LEAD_MANAGEMENT_LIST: '/lead-management/list',
    LOCATIONS: '/locations',
    DOUBLETICK: '/doubletick',
    DOUBLETICK_CONVERSATIONS: '/doubletick/conversations',
    DOUBLETICK_LEADS: '/doubletick/leads',
    DOUBLETICK_AREAS: '/doubletick/areas',
    DOUBLETICK_AREA_MAP: '/doubletick/area-map',
    BOTS: '/bots',
    BOTS_BUILDER: '/bots/builder',
    BOTS_BUILDER_FULLSCREEN: '/bots/builder/fullscreen',
    BOTS_FLOWS: '/bots/flows',
    BOTS_NODES: '/bots/nodes',
    BOTS_NODE_OPTIONS: '/bots/node-options',
    BOTS_TRANSITIONS: '/bots/transitions',
    BOTS_TRIGGERS: '/bots/triggers',
    BOTS_TEMPLATES: '/bots/templates',
    BOTS_DATA_SOURCES: '/bots/data-sources',
    BOTS_HANDOVER_RULES: '/bots/handover-rules',
    BOTS_FALLBACK_RULES: '/bots/fallback-rules',
    BOTS_SESSIONS: '/bots/sessions',
    BOTS_SESSION_VARIABLES: '/bots/session-variables',
    BOTS_LOGS: '/bots/logs',
    BOTS_API_CALL_LOGS: '/bots/api-call-logs',
    BOTS_SHEET_SYNC_LOGS: '/bots/sheet-sync-logs',
    BOTS_INTEGRATIONS: '/bots/integrations',
    BOTS_SIMULATOR: '/bots/simulator',
    NOTIFICATIONS: '/notifications',
    
};

