# Generated by Django 4.2.27 on 2026-03-29 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_online_user_last_login_at_user_last_seen_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoginHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("login_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="success", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Login History",
                "verbose_name_plural": "User Login Histories",
                "ordering": ["-login_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "login_at"],
                        name="accounts_us_user_id_a74642_idx",
                    )
                ],
            },
        ),
    ]
