# Generated by Django 4.2.27 on 2026-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userloginhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(
                blank=True,
                help_text="Registration token for Firebase Cloud Messaging for this manager.",
                null=True,
            ),
        ),
    ]
