# Generated by Django 4.2.28 on 2026-05-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('area_manager', 'Area Manager'), ('spa_manager', 'SPA Manager')], db_index=True, max_length=30),
        ),
    ]
