# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_phone_number"),
        ("branches", "0004_alter_branch_spa_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="area_branches",
            field=models.ManyToManyField(
                blank=True,
                help_text="SPA branches this area manager can see.",
                related_name="area_managers",
                to="branches.branch",
            ),
        ),
    ]
