# Generated by Django 4.2.28 on 2026-03-20 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("contacts", "0001_initial"),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Phone number of the external party (caller or callee).",
                        max_length=20,
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("incoming", "Incoming"),
                            ("outgoing", "Outgoing"),
                            ("missed", "Missed"),
                            ("rejected", "Rejected"),
                        ],
                        help_text="Type of call: incoming, outgoing, missed, or rejected.",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        help_text="Call duration in seconds. 0 for missed or rejected calls."
                    ),
                ),
                (
                    "sim_slot",
                    models.IntegerField(
                        help_text="SIM slot that handled this call: 1 or 2."
                    ),
                ),
                (
                    "call_time",
                    models.DateTimeField(help_text="Exact date and time of the call."),
                ),
                (
                    "call_hash",
                    models.CharField(
                        help_text="Unique hash for deduplication. Prevents duplicate call log entries.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The branch where this call was captured. Inherited from device.branch.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="branches.branch",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Known contact linked by phone number (auto-matched by last 10 digits).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="contacts.contact",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="The device that captured this call log.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Log",
                "verbose_name_plural": "Call Logs",
                "db_table": "call_logs",
                "ordering": ["-call_time"],
                "indexes": [
                    models.Index(
                        fields=["branch", "call_time"],
                        name="call_logs_branch__cc9f1f_idx",
                    ),
                    models.Index(
                        fields=["call_time"], name="call_logs_call_ti_26cba0_idx"
                    ),
                    models.Index(
                        fields=["branch"], name="call_logs_branch__913b2c_idx"
                    ),
                    models.Index(
                        fields=["device"], name="call_logs_device__e04f8f_idx"
                    ),
                    models.Index(
                        fields=["phone_number"], name="call_logs_phone_n_5db794_idx"
                    ),
                    models.Index(
                        fields=["call_hash"], name="call_logs_call_ha_0d89db_idx"
                    ),
                ],
            },
        ),
    ]
