# Generated by Django 4.2.27 on 2026-04-21 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0004_alter_branch_spa_name"),
        ("calllogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="call_type",
            field=models.CharField(
                choices=[
                    ("incoming", "Incoming"),
                    ("outgoing", "Outgoing"),
                    ("missed", "Missed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                help_text="Type of call: incoming, outgoing, missed, or rejected.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MissedCallFollowUp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_followed_up", models.BooleanField(db_index=True, default=False)),
                ("first_followup_time", models.DateTimeField(blank=True, null=True)),
                ("followup_attempt_count", models.IntegerField(default=0)),
                (
                    "sla_status",
                    models.CharField(
                        choices=[
                            ("GOOD", "Within 10 mins"),
                            ("OK", "Within 30 mins"),
                            ("LATE", "Within 1 hour"),
                            ("MISSED", "No follow-up / > 1 hour"),
                        ],
                        db_index=True,
                        default="MISSED",
                        max_length=10,
                    ),
                ),
                ("notification_step", models.IntegerField(db_index=True, default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missed_call_followups",
                        to="branches.branch",
                    ),
                ),
                (
                    "followup_call",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"call_type": "outgoing"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serves_as_followup",
                        to="calllogs.calllog",
                    ),
                ),
                (
                    "missed_call",
                    models.OneToOneField(
                        limit_choices_to={"call_type": "missed"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followup_status",
                        to="calllogs.calllog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Missed Call Follow-Up",
                "verbose_name_plural": "Missed Call Follow-Ups",
                "db_table": "missed_call_followups",
                "indexes": [
                    models.Index(
                        fields=["branch", "is_followed_up"],
                        name="missed_call_branch__295c4c_idx",
                    ),
                    models.Index(
                        fields=["sla_status"], name="missed_call_sla_sta_04eaee_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="missed_call_created_1d826f_idx"
                    ),
                ],
            },
        ),
    ]
