# Generated by Django 4.2.27 on 2026-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calllogs", "0002_alter_calllog_call_type_missedcallfollowup"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="phone_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stores the last 10 digits only for robust cross-format matching.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(
                fields=["phone_normalized"], name="call_logs_phone_n_1bbab3_idx"
            ),
        ),
    ]
