# Generated by Django 4.2.28 on 2026-06-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calllogs", "0003_calllog_phone_normalized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missedcallfollowup",
            name="followup_call",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"call_type__in": ["outgoing", "incoming"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="serves_as_followup",
                to="calllogs.calllog",
            ),
        ),
        migrations.AlterField(
            model_name="missedcallfollowup",
            name="sla_status",
            field=models.CharField(
                choices=[
                    ("GOOD", "Within 10 mins"),
                    ("OK", "Within 30 mins"),
                    ("LATE", "Within 1 hour"),
                    ("MISSED", "No follow-up / > 1 hour"),
                    ("CUSTOMER_RECALL", "Customer recalled"),
                ],
                db_index=True,
                default="MISSED",
                max_length=20,
            ),
        ),
    ]
