# Generated by Django 4.2.28 on 2026-06-03 11:59

from django.db import migrations

def resolve_historical_followups(apps, schema_editor):
    # Only run on databases with SQL execute (e.g. postgresql)
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                UPDATE missed_call_followups
                SET 
                  followup_call_id = sub.id,
                  is_followed_up = true,
                  first_followup_time = sub.call_time,
                  followup_attempt_count = 1,
                  sla_status = CASE 
                    WHEN sub.call_type = 'incoming' THEN 'CUSTOMER_RECALL'
                    ELSE (
                      CASE 
                        WHEN EXTRACT(EPOCH FROM (sub.call_time - missed.call_time)) / 60 <= 10 THEN 'GOOD'
                        WHEN EXTRACT(EPOCH FROM (sub.call_time - missed.call_time)) / 60 <= 30 THEN 'OK'
                        WHEN EXTRACT(EPOCH FROM (sub.call_time - missed.call_time)) / 60 <= 60 THEN 'LATE'
                        ELSE 'MISSED'
                      END
                    )
                  END
                FROM call_logs missed
                CROSS JOIN LATERAL (
                  SELECT c.id, c.call_time, c.call_type
                  FROM call_logs c
                  WHERE c.branch_id = missed.branch_id
                    AND c.phone_normalized = missed.phone_normalized
                    AND c.call_type IN ('incoming', 'outgoing')
                    AND c.call_time > missed.call_time
                  ORDER BY c.call_time ASC
                  LIMIT 1
                ) sub
                WHERE missed_call_followups.missed_call_id = missed.id
                  AND missed_call_followups.is_followed_up = false;
            """)
    else:
        # Fallback for SQLite (e.g. during testing)
        MissedCallFollowUp = apps.get_model('calllogs', 'MissedCallFollowUp')
        CallLog = apps.get_model('calllogs', 'CallLog')
        pendings = MissedCallFollowUp.objects.filter(is_followed_up=False)
        for pending in pendings:
            m_log = pending.missed_call
            if not m_log:
                continue
            existing_followup_call = CallLog.objects.filter(
                branch_id=pending.branch_id,
                phone_normalized=m_log.phone_normalized,
                call_type__in=["outgoing", "incoming"],
                call_time__gt=m_log.call_time
            ).order_by('call_time').first()

            if existing_followup_call:
                if existing_followup_call.call_type == "incoming":
                    status = "CUSTOMER_RECALL"
                else:
                    time_diff = existing_followup_call.call_time - m_log.call_time
                    diff_minutes = time_diff.total_seconds() / 60
                    status = "GOOD" if diff_minutes <= 10 else "OK" if diff_minutes <= 30 else "LATE" if diff_minutes <= 60 else "MISSED"
                
                pending.followup_call = existing_followup_call
                pending.is_followed_up = True
                pending.first_followup_time = existing_followup_call.call_time
                pending.followup_attempt_count = 1
                pending.sla_status = status
                pending.save()

class Migration(migrations.Migration):

    dependencies = [
        ("calllogs", "0004_alter_missedcallfollowup_followup_call_and_more"),
    ]

    operations = [
        migrations.RunPython(resolve_historical_followups, reverse_code=migrations.RunPython.noop),
    ]
