# Generated by Django 4.2.28 on 2026-03-20 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calllogs", "0001_initial"),
        ("branches", "0001_initial"),
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadManagement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ringing", "Ringing"),
                            ("coming", "Coming"),
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current follow-up status of this lead.",
                        max_length=50,
                    ),
                ),
                (
                    "booking_date",
                    models.DateField(
                        blank=True,
                        help_text="Scheduled visit/appointment date. Only used for 'coming' or 'interested' leads.",
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Notes from branch manager about follow-up conversation.",
                        null=True,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The branch this lead belongs to. Auto-set from calllog.branch.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="branches.branch",
                    ),
                ),
                (
                    "calllog",
                    models.OneToOneField(
                        blank=True,
                        help_text="The originating call log for this lead.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead",
                        to="calllogs.calllog",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Known contact for this lead (auto-matched from call log's phone number).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this lead (system user for auto-created leads).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this lead's status.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "lead_management",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["calllog"], name="lead_manage_calllog_f864d0_idx"
                    ),
                    models.Index(
                        fields=["branch"], name="lead_manage_branch__8f7f1b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="lead_manage_status_1595ac_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="lead_manage_created_30e84e_idx"
                    ),
                ],
            },
        ),
    ]
