# Generated by Django 4.2.27 on 2026-07-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branches", "0005_add_location_fk_fields_to_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteFormConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("website_name", models.CharField(db_index=True, max_length=150)),
                ("website_url", models.URLField(max_length=500)),
                (
                    "form_key",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                (
                    "form_title",
                    models.CharField(default="Book Appointment", max_length=150),
                ),
                ("primary_color", models.CharField(default="#BD9B5F", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#FFFFFF", max_length=20),
                ),
                ("button_color", models.CharField(default="#25D366", max_length=20)),
                ("text_color", models.CharField(default="#111111", max_length=20)),
                ("border_radius", models.CharField(default="16px", max_length=20)),
                ("font_family", models.CharField(default="Inter", max_length=100)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("custom", "Custom"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "submit_button_text",
                    models.CharField(default="Submit", max_length=80),
                ),
                (
                    "success_message",
                    models.CharField(
                        default="Thank you. Our team will contact you shortly.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Spa branch where leads from this website form should route.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_form_configurations",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_website_form_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Website Form Configuration",
                "verbose_name_plural": "Website Form Configurations",
                "db_table": "website_form_configurations",
                "ordering": ["website_name"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteLead",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("website_name", models.CharField(db_index=True, max_length=150)),
                ("website_url", models.URLField(max_length=500)),
                ("form_key", models.CharField(db_index=True, max_length=80)),
                ("customer_name", models.CharField(max_length=150)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("address", models.CharField(max_length=20)),
                ("notes", models.CharField(blank=True, max_length=20)),
                ("submitted_from_url", models.URLField(blank=True, max_length=1000)),
                ("referrer_url", models.URLField(blank=True, max_length=1000)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "routing_status",
                    models.CharField(
                        choices=[
                            ("routed", "Routed"),
                            ("pending_configuration", "Pending Configuration"),
                            ("unassigned", "Unassigned"),
                        ],
                        db_index=True,
                        default="unassigned",
                        max_length=40,
                    ),
                ),
                (
                    "notification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("not_required", "Not Required"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notification_error", models.TextField(blank=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_website_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_leads",
                        to="branches.branch",
                    ),
                ),
                (
                    "form_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="webLead.websiteformconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Website Lead",
                "verbose_name_plural": "Website Leads",
                "db_table": "website_leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteFormDailyStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("website_name", models.CharField(db_index=True, max_length=150)),
                ("website_url", models.URLField(max_length=500)),
                ("form_key", models.CharField(db_index=True, max_length=80)),
                ("total_submissions", models.PositiveIntegerField(default=0)),
                ("successful_submissions", models.PositiveIntegerField(default=0)),
                ("duplicate_submissions", models.PositiveIntegerField(default=0)),
                ("rejected_submissions", models.PositiveIntegerField(default=0)),
                ("converted_count", models.PositiveIntegerField(default=0)),
                ("notification_sent_count", models.PositiveIntegerField(default=0)),
                ("notification_failed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_form_daily_stats",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Website Form Daily Stat",
                "verbose_name_plural": "Website Form Daily Stats",
                "db_table": "website_form_daily_stats",
                "ordering": ["-date", "website_name"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteLeadActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_lead_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="webLead.websiteformconfiguration",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="webLead.websitelead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Website Lead Activity",
                "verbose_name_plural": "Website Lead Activities",
                "db_table": "website_lead_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="website_lea_action_5705b4_idx",
                    ),
                    models.Index(
                        fields=["lead", "created_at"],
                        name="website_lea_lead_id_891a8a_idx",
                    ),
                    models.Index(
                        fields=["form_configuration", "created_at"],
                        name="website_lea_form_co_912df0_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="websitelead",
            index=models.Index(
                fields=["branch", "created_at"], name="website_lea_branch__698f9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websitelead",
            index=models.Index(
                fields=["form_key", "phone", "created_at"],
                name="website_lea_form_ke_05edc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="websitelead",
            index=models.Index(
                fields=["website_name", "created_at"],
                name="website_lea_website_c04b1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="websitelead",
            index=models.Index(
                fields=["status", "routing_status"],
                name="website_lea_status_f46233_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="websitelead",
            index=models.Index(
                fields=["notification_status"], name="website_lea_notific_f091bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websiteformdailystats",
            index=models.Index(
                fields=["date", "branch"], name="website_for_date_219719_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websiteformdailystats",
            index=models.Index(
                fields=["date", "website_name"], name="website_for_date_40a327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websiteformdailystats",
            index=models.Index(
                fields=["date", "form_key"], name="website_for_date_2fb218_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="websiteformdailystats",
            unique_together={("date", "branch", "form_key")},
        ),
        migrations.AddIndex(
            model_name="websiteformconfiguration",
            index=models.Index(
                fields=["branch", "is_active"], name="website_for_branch__680bbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websiteformconfiguration",
            index=models.Index(
                fields=["website_name"], name="website_for_website_49d1eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websiteformconfiguration",
            index=models.Index(
                fields=["website_url"], name="website_for_website_45f58c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websiteformconfiguration",
            index=models.Index(
                fields=["created_at"], name="website_for_created_75f814_idx"
            ),
        ),
    ]
