# Generated by Django 4.2.28 on 2026-03-20 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique device identifier assigned after successful registration.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Secret key for HMAC signing. Never expose in API responses.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "registration_token",
                    models.CharField(
                        blank=True,
                        help_text="Short token displayed to admin for Android app registration.",
                        max_length=32,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_registered",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the device has been claimed by the Android app.",
                    ),
                ),
                (
                    "sim_1_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "sim_2_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        blank=True,
                        help_text="Registration token for Firebase Cloud Messaging.",
                        null=True,
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this device successfully synced call logs.",
                        null=True,
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last heartbeat ping received from this device.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active devices can sync data."
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Blocked devices are rejected at API auth level.",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The branch this device is physically installed at.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "db_table": "devices",
                "indexes": [
                    models.Index(
                        fields=["device_id"], name="devices_device__c4b5e4_idx"
                    ),
                    models.Index(fields=["branch"], name="devices_branch__9fc335_idx"),
                    models.Index(
                        fields=["is_active"], name="devices_is_acti_9ea4e7_idx"
                    ),
                    models.Index(
                        fields=["is_registered"], name="devices_is_regi_a21f25_idx"
                    ),
                    models.Index(
                        fields=["registration_token"], name="devices_registr_16a621_idx"
                    ),
                ],
            },
        ),
    ]
