# Generated by Django 4.2.27 on 2026-03-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="phone_name",
            field=models.CharField(
                blank=True,
                help_text="Custom name for the phone (e.g. 'Reception Desk').",
                max_length=255,
                null=True,
            ),
        ),
    ]
