# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_device_phone_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="android_id",
            field=models.CharField(
                blank=True,
                help_text="Stable Android identifier used for self-healing credential recovery.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["android_id"], name="devices_android_id_idx"),
        ),
    ]
