# Generated by Codex on 2026-05-27

from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_last_sync_history(apps, schema_editor):
    Device = apps.get_model("devices", "Device")
    Lastsynchistory = apps.get_model("devices", "Lastsynchistory")

    Lastsynchistory.objects.bulk_create(
        [
            Lastsynchistory(device_id=device.id, last_sync_time=device.last_sync)
            for device in Device.objects.all()
        ],
        ignore_conflicts=True,
    )


def remove_backfilled_last_sync_history(apps, schema_editor):
    Lastsynchistory = apps.get_model("devices", "Lastsynchistory")
    Lastsynchistory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_device_android_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lastsynchistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The timestamp of the last successful synchronization.",
                        null=True,
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        help_text="The device this sync history belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_sync_history",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Last Sync History",
                "verbose_name_plural": "Last Sync Histories",
                "db_table": "last_sync_history",
            },
        ),
        migrations.RunPython(
            backfill_last_sync_history,
            remove_backfilled_last_sync_history,
        ),
    ]
