# Generated by Django 4.2.28 on 2026-07-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_devicestoragereport"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="devicestoragereport",
            new_name="device_stor_device__3dba9e_idx",
            old_name="device_stor_device__fa624d_idx",
        ),
        migrations.RenameIndex(
            model_name="devicestoragereport",
            new_name="device_stor_storage_40873e_idx",
            old_name="device_stor_storage_43b142_idx",
        ),
        migrations.RemoveField(
            model_name="devicestoragereport",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="devicestoragereport",
            name="updated_at",
        ),
    ]
