# Generated by Django 5.2.16 on 2026-08-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0005_add_location_fk_fields_to_branch"),
        (
            "devices",
            "0006_rename_device_stor_device__fa624d_idx_device_stor_device__3dba9e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["branch", "last_heartbeat"], name="devices_branch_heartbeat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["branch", "last_sync"], name="devices_branch_sync_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["last_heartbeat"], name="devices_last_heartbeat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["last_sync"], name="devices_last_sync_idx"),
        ),
        migrations.AddIndex(
            model_name="lastsynchistory",
            index=models.Index(fields=["last_sync_time"], name="lastsync_time_idx"),
        ),
    ]
