# Generated by Django 4.2.28 on 2026-06-20 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=160),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=180),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "ordering": ["city__state__name", "city__name", "priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="AreaAlias",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alias", models.CharField(max_length=180)),
                (
                    "normalized_alias",
                    models.CharField(db_index=True, editable=False, max_length=200),
                ),
                ("language", models.CharField(blank=True, max_length=30, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Area Alias",
                "verbose_name_plural": "Area Aliases",
                "ordering": [
                    "area__city__state__name",
                    "area__city__name",
                    "area__name",
                    "alias",
                ],
            },
        ),
        migrations.CreateModel(
            name="BranchCoverageArea",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(db_index=True, default=0)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Branch Coverage Area",
                "verbose_name_plural": "Branch Coverage Areas",
                "ordering": ["priority", "area__city__name", "area__name"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=140),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=160),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["state__name", "priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="CityAlias",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alias", models.CharField(max_length=160)),
                (
                    "normalized_alias",
                    models.CharField(db_index=True, editable=False, max_length=180),
                ),
                ("language", models.CharField(blank=True, max_length=30, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "City Alias",
                "verbose_name_plural": "City Aliases",
                "ordering": ["city__state__name", "city__name", "alias"],
            },
        ),
        migrations.CreateModel(
            name="LocationGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=180),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=200),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Location Group",
                "verbose_name_plural": "Location Groups",
                "ordering": ["city__state__name", "city__name", "priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="LocationGroupArea",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("priority", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Location Group Area",
                "verbose_name_plural": "Location Group Areas",
                "ordering": [
                    "group__city__name",
                    "group__priority",
                    "priority",
                    "area__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationMatchIgnorePhrase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phrase", models.CharField(max_length=180)),
                (
                    "normalized_phrase",
                    models.CharField(db_index=True, editable=False, max_length=200),
                ),
                (
                    "phrase_type",
                    models.CharField(
                        choices=[
                            ("greeting", "Greeting"),
                            ("general", "General"),
                            ("job", "Job Inquiry"),
                            ("service", "Service Inquiry"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=30,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=30, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Location Match Ignore Phrase",
                "verbose_name_plural": "Location Match Ignore Phrases",
                "ordering": ["phrase_type", "phrase"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=140),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=160),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"],
                        name="locations_s_is_acti_ef52c9_idx",
                    ),
                    models.Index(fields=["slug"], name="locations_s_slug_c8a448_idx"),
                    models.Index(fields=["code"], name="locations_s_code_f8d7d5_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("normalized_name",),
                name="locations_state_unique_active_normalized_name",
            ),
        ),
        migrations.AddIndex(
            model_name="locationmatchignorephrase",
            index=models.Index(
                fields=["normalized_phrase"], name="locations_l_normali_ef1c6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationmatchignorephrase",
            index=models.Index(
                fields=["phrase_type", "is_active"],
                name="locations_l_phrase__658b15_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationmatchignorephrase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("normalized_phrase", "phrase_type"),
                name="locations_ignorephrase_unique_active_phrase_type",
            ),
        ),
        migrations.AddField(
            model_name="locationgrouparea",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_groups",
                to="locations.area",
            ),
        ),
        migrations.AddField(
            model_name="locationgrouparea",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_areas",
                to="locations.locationgroup",
            ),
        ),
        migrations.AddField(
            model_name="locationgroup",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="location_groups",
                to="locations.city",
            ),
        ),
        migrations.AddField(
            model_name="cityalias",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="locations.city",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="locations.state",
            ),
        ),
        migrations.AddField(
            model_name="branchcoveragearea",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branch_coverages",
                to="locations.area",
            ),
        ),
        migrations.AddField(
            model_name="branchcoveragearea",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_branch_coverages",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="branchcoveragearea",
            name="location_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_coverages",
                to="locations.locationgroup",
            ),
        ),
        migrations.AddField(
            model_name="areaalias",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="locations.area",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="areas",
                to="locations.city",
            ),
        ),
        migrations.AddIndex(
            model_name="locationgrouparea",
            index=models.Index(
                fields=["group", "priority"], name="locations_l_group_i_0c687a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationgrouparea",
            index=models.Index(fields=["area"], name="locations_l_area_id_7b6df8_idx"),
        ),
        migrations.AddIndex(
            model_name="locationgrouparea",
            index=models.Index(
                fields=["is_primary"], name="locations_l_is_prim_dda378_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationgrouparea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("group", "area"),
                name="locations_grouparea_unique_active_group_area",
            ),
        ),
        migrations.AddIndex(
            model_name="locationgroup",
            index=models.Index(
                fields=["city", "is_active"], name="locations_l_city_id_392a2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationgroup",
            index=models.Index(
                fields=["city", "priority"], name="locations_l_city_id_fd90bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationgroup",
            index=models.Index(fields=["slug"], name="locations_l_slug_a3128b_idx"),
        ),
        migrations.AddConstraint(
            model_name="locationgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("city", "normalized_name"),
                name="locations_group_unique_active_city_normalized_name",
            ),
        ),
        migrations.AddIndex(
            model_name="cityalias",
            index=models.Index(
                fields=["normalized_alias"], name="locations_c_normali_e470ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cityalias",
            index=models.Index(
                fields=["city", "is_active"], name="locations_c_city_id_f47d21_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cityalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("city", "normalized_alias"),
                name="locations_cityalias_unique_active_city_alias",
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["state", "is_active"], name="locations_c_state_i_837821_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["state", "priority"], name="locations_c_state_i_4cd141_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["slug"], name="locations_c_slug_0d00a7_idx"),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("state", "normalized_name"),
                name="locations_city_unique_active_state_normalized_name",
            ),
        ),
        migrations.AddIndex(
            model_name="branchcoveragearea",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="locations_b_content_f6885c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="branchcoveragearea",
            index=models.Index(
                fields=["area", "is_active"], name="locations_b_area_id_8aa0ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchcoveragearea",
            index=models.Index(
                fields=["location_group", "is_active"],
                name="locations_b_locatio_b74a4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="branchcoveragearea",
            index=models.Index(
                fields=["is_primary"], name="locations_b_is_prim_59f129_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="branchcoveragearea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("content_type", "object_id", "area"),
                name="locations_branchcoverage_unique_active_branch_area",
            ),
        ),
        migrations.AddIndex(
            model_name="areaalias",
            index=models.Index(
                fields=["normalized_alias"], name="locations_a_normali_f90695_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="areaalias",
            index=models.Index(
                fields=["area", "is_active"], name="locations_a_area_id_c9bbd1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="areaalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("area", "normalized_alias"),
                name="locations_areaalias_unique_active_area_alias",
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["city", "is_active"], name="locations_a_city_id_a15902_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["city", "priority"], name="locations_a_city_id_8fbdce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["slug"], name="locations_a_slug_a4b053_idx"),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("city", "normalized_name"),
                name="locations_area_unique_active_city_normalized_name",
            ),
        ),
    ]
