# Generated by Django 4.2.28 on 2026-03-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_online", models.BooleanField(default=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("battery_level", models.IntegerField(blank=True, null=True)),
                ("signal_strength", models.IntegerField(blank=True, null=True)),
                ("storage_used_mb", models.FloatField(default=0.0)),
                ("app_version", models.CharField(default="1.0.0", max_length=20)),
                (
                    "sim_1_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "sim_2_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sync_failures", models.IntegerField(default=0)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "device_health",
            },
        ),
        migrations.CreateModel(
            name="DeviceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("offline", "Device Offline"),
                            ("sim_change", "SIM Card Changed"),
                            ("sync_failure", "Sync Failure"),
                            ("battery_low", "Battery Low"),
                            ("storage_full", "Storage Full"),
                            ("permission_denied", "Permission Denied"),
                            ("app_crash", "App Crash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "device_events",
                "indexes": [
                    models.Index(
                        fields=["event_type", "resolved"],
                        name="device_even_event_t_dc74c8_idx",
                    ),
                    models.Index(
                        fields=["device", "created_at"],
                        name="device_even_device__3b2318_idx",
                    ),
                ],
            },
        ),
    ]
