# Generated by Django 4.2.27 on 2026-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicehealth",
            name="notified_24h",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="devicehealth",
            name="notified_2h",
            field=models.BooleanField(default=False),
        ),
    ]
