# Generated by Django 4.2.27 on 2026-06-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_devicehealth_notified_24h_devicehealth_notified_2h"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("offline", "Device Offline"),
                    ("sim_change", "SIM Card Changed"),
                    ("sync_failure", "Sync Failure"),
                    ("battery_low", "Battery Low"),
                    ("storage_full", "Storage Full"),
                    ("network_weak", "Weak Network Signal"),
                    ("permission_denied", "Permission Denied"),
                    ("app_crash", "App Crash"),
                ],
                max_length=20,
            ),
        ),
    ]
