# Generated by Django 5.2.16 on 2026-08-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_device_devices_branch_heartbeat_idx_and_more"),
        ("monitoring", "0011_api_observability"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="devicehealth",
            index=models.Index(
                fields=["is_online", "last_heartbeat"], name="dev_health_online_hb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicehealth",
            index=models.Index(
                fields=["last_heartbeat"], name="dev_health_last_hb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicehealth",
            index=models.Index(fields=["last_sync"], name="dev_health_last_sync_idx"),
        ),
        migrations.AddIndex(
            model_name="devicehealth",
            index=models.Index(
                fields=["pending_call_count"], name="dev_health_pending_idx"
            ),
        ),
    ]
