# Generated by Django 4.2.28 on 2026-06-20 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doubletick", "0007_seed_doubletick_channels"),
        ("branches", "0004_alter_branch_spa_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "bot_type",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("job", "Job Inquiry"),
                            ("support", "Support"),
                            ("follow_up", "Follow Up"),
                            ("branch", "Branch Specific"),
                            ("city", "City Specific"),
                            ("generic", "Generic"),
                        ],
                        default="booking",
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("default_language", models.CharField(default="en", max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.IntegerField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "bots",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="BotDataSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("states", "States"),
                            ("cities", "Cities"),
                            ("areas", "Areas"),
                            ("branches", "Branches"),
                            ("doubletick_areas", "DoubleTick Areas"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "bot_data_sources",
            },
        ),
        migrations.CreateModel(
            name="BotFlow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "db_table": "bot_flows",
                "ordering": ["bot__name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="BotIntegration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("google_sheets", "Google Sheets"),
                            ("webhook_api", "Webhook API"),
                            ("internal_api", "Internal API"),
                            ("doubletick", "DoubleTick"),
                        ],
                        max_length=50,
                    ),
                ),
                ("credentials", models.JSONField(blank=True, default=dict)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "bot_integrations",
            },
        ),
        migrations.CreateModel(
            name="BotNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("text_message", "Text Message"),
                            ("template_message", "Template Message"),
                            ("question", "Question"),
                            ("option_buttons", "Option Buttons"),
                            ("interactive_list", "Interactive List"),
                            ("dynamic_state_select", "Dynamic State Select"),
                            ("dynamic_city_select", "Dynamic City Select"),
                            ("dynamic_area_select", "Dynamic Area Select"),
                            ("dynamic_branch_select", "Dynamic Branch Select"),
                            ("collect_input", "Collect Input"),
                            ("condition", "Condition"),
                            ("match_location", "Match Location"),
                            ("assign_lead", "Assign Lead"),
                            ("broadcast_lead", "Broadcast Lead"),
                            ("round_robin_assign", "Round Robin Assign"),
                            ("manual_handover", "Manual Handover"),
                            ("api_call", "API Call"),
                            ("google_sheet_append", "Google Sheet Append"),
                            ("tag_lead", "Tag Lead"),
                            ("update_lead_status", "Update Lead Status"),
                            ("delay", "Delay"),
                            ("end", "End"),
                            ("fallback", "Fallback"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("message_text", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=20)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("position", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "default_next_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_previous_nodes",
                        to="bots.botnode",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="bots.botflow",
                    ),
                ),
            ],
            options={
                "db_table": "bot_nodes",
                "ordering": ["flow", "order", "position", "name"],
            },
        ),
        migrations.CreateModel(
            name="BotSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("selected_state", models.CharField(blank=True, max_length=100)),
                ("selected_city", models.CharField(blank=True, max_length=100)),
                ("selected_area", models.CharField(blank=True, max_length=100)),
                ("intent", models.CharField(blank=True, db_index=True, max_length=100)),
                ("language", models.CharField(blank=True, max_length=20)),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("last_customer_message", models.TextField(blank=True)),
                ("last_bot_message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("handed_over", "Handed Over"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("fallback_count", models.PositiveIntegerField(default=0)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="bots.bot",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_sessions",
                        to="doubletick.doubletickconversation",
                    ),
                ),
                (
                    "current_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="bots.botnode",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_sessions",
                        to="doubletick.doubletickcustomer",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="bots.botflow",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_sessions",
                        to="doubletick.doubleticklead",
                    ),
                ),
                (
                    "selected_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_sessions",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "db_table": "bot_sessions",
            },
        ),
        migrations.CreateModel(
            name="BotTrigger",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("first_inbound", "First Inbound Customer Message"),
                            ("keyword", "Keyword Match"),
                            ("lead_created", "Lead Created"),
                            ("location_missing", "Location Missing"),
                            ("area_matched", "Area Matched"),
                            ("manual_action", "Manual CRM Action"),
                            ("status_changed", "Status Changed"),
                            ("follow_up_due", "Follow Up Due"),
                            ("abandoned", "Abandoned Conversation"),
                            ("campaign_source", "Campaign Source"),
                            ("channel", "WABA Channel"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("source_campaign", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("lead_type", models.CharField(blank=True, max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="bots.bot",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_triggers",
                        to="branches.branch",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_triggers",
                        to="doubletick.doubletickchannel",
                    ),
                ),
            ],
            options={
                "db_table": "bot_triggers",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotTransition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="bots.botflow",
                    ),
                ),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="bots.botnode",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="bots.botnode",
                    ),
                ),
            ],
            options={
                "db_table": "bot_transitions",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotSheetSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_payload", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sheet_sync_logs",
                        to="bots.botintegration",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_sheet_sync_logs",
                        to="doubletick.doubleticklead",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sheet_sync_logs",
                        to="bots.botsession",
                    ),
                ),
            ],
            options={
                "db_table": "bot_sheet_sync_logs",
            },
        ),
        migrations.CreateModel(
            name="BotNodeOption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "payload_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("action", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "next_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_options",
                        to="bots.botnode",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="bots.botnode",
                    ),
                ),
            ],
            options={
                "db_table": "bot_node_options",
                "ordering": ["node", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="BotMessageTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("language", models.CharField(default="en", max_length=20)),
                ("template_type", models.CharField(default="text", max_length=50)),
                ("text", models.TextField()),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "db_table": "bot_message_templates",
            },
        ),
        migrations.CreateModel(
            name="BotHandoverRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "assign_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_handover_rules",
                        to="branches.branch",
                    ),
                ),
                (
                    "assign_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_handover_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handover_rules",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "db_table": "bot_handover_rules",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="BotFallbackRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("retry_number", models.PositiveIntegerField(default=1)),
                ("message_text", models.TextField(blank=True)),
                ("handover_after", models.PositiveIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fallback_rules",
                        to="bots.bot",
                    ),
                ),
                (
                    "next_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_rules",
                        to="bots.botnode",
                    ),
                ),
            ],
            options={
                "db_table": "bot_fallback_rules",
                "ordering": ["retry_number", "name"],
            },
        ),
        migrations.CreateModel(
            name="BotExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("sent", "Sent"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=30,
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_execution_logs",
                        to="doubletick.doubletickconversation",
                    ),
                ),
                (
                    "incoming_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_incoming_logs",
                        to="doubletick.doubletickmessage",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_execution_logs",
                        to="doubletick.doubleticklead",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="bots.botnode",
                    ),
                ),
                (
                    "outbound_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_outbound_logs",
                        to="doubletick.doubletickmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="bots.botsession",
                    ),
                ),
            ],
            options={
                "db_table": "bot_execution_logs",
            },
        ),
        migrations.CreateModel(
            name="BotApiCallLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("method", models.CharField(default="POST", max_length=20)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_call_logs",
                        to="bots.botintegration",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_call_logs",
                        to="bots.botnode",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_call_logs",
                        to="bots.botsession",
                    ),
                ),
            ],
            options={
                "db_table": "bot_api_call_logs",
            },
        ),
        migrations.CreateModel(
            name="BotSessionVariable",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_variables",
                        to="bots.botsession",
                    ),
                ),
            ],
            options={
                "db_table": "bot_session_variables",
                "unique_together": {("session", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="botsession",
            index=models.Index(
                fields=["conversation", "status"], name="bot_session_conv_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botsession",
            index=models.Index(
                fields=["lead", "status"], name="bot_session_lead_status_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="botmessagetemplate",
            unique_together={("bot", "name", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="botflow",
            unique_together={("bot", "version")},
        ),
        migrations.AddIndex(
            model_name="botexecutionlog",
            index=models.Index(fields=["idempotency_key"], name="bot_exec_idem_idx"),
        ),
    ]
