# Generated by Django 5.2.16 on 2026-08-13 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0006_branchoperatinghours"),
        ("calllogs", "0007_dashboard_performance_indexes"),
        ("contacts", "0001_initial"),
        ("devices", "0007_device_devices_branch_heartbeat_idx_and_more"),
        ("doubletick", "0009_link_routing_profile_to_location_area"),
        ("leadmanagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "routing_type",
                    models.CharField(
                        choices=[
                            ("night", "Night"),
                            ("closed_spa", "Closed Spa"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="night",
                        max_length=30,
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("max_recommendations", models.PositiveSmallIntegerField(default=3)),
                ("cooldown_minutes", models.PositiveIntegerField(default=60)),
                ("whatsapp_enabled", models.BooleanField(default=True)),
                ("dry_run", models.BooleanField(default=True)),
                ("priority", models.IntegerField(db_index=True, default=0)),
                ("template_name", models.CharField(blank=True, max_length=150)),
                (
                    "template_language",
                    models.CharField(blank=True, default="en", max_length=20),
                ),
                ("template_version", models.CharField(blank=True, max_length=50)),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_until", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Routing Rule",
                "verbose_name_plural": "Routing Rules",
                "db_table": "callrouting_rules",
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["enabled", "routing_type", "priority"],
                        name="cr_rule_enabled_type_pri_idx",
                    ),
                    models.Index(
                        fields=["active_from", "active_until"],
                        name="cr_rule_active_window_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutingRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "routing_type",
                    models.CharField(
                        choices=[
                            ("night", "Night"),
                            ("closed_spa", "Closed Spa"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="night",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("routed", "Routed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("invalid_phone", "Invalid Phone"),
                            ("duplicate", "Duplicate"),
                            ("customer_cooldown", "Customer Cooldown"),
                            ("no_rule", "No Rule"),
                            ("source_spa_open", "Source Spa Open"),
                            ("no_candidate", "No Candidate"),
                            ("dry_run", "Dry Run"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "normalized_phone",
                    models.CharField(blank=True, db_index=True, max_length=15),
                ),
                ("source_branch_open", models.BooleanField(blank=True, null=True)),
                ("source_open_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call_time",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Call time snapshot used for routing decisions.",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "call_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_request",
                        to="calllogs.calllog",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_requests",
                        to="contacts.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_requests",
                        to="leadmanagement.leadmanagement",
                    ),
                ),
                (
                    "source_branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch relation snapshot from the source CallLog for filtering and audit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_routing_requests",
                        to="branches.branch",
                    ),
                ),
                (
                    "source_device",
                    models.ForeignKey(
                        blank=True,
                        help_text="Device relation snapshot from the source CallLog for filtering and audit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_requests",
                        to="devices.device",
                    ),
                ),
                (
                    "routing_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_requests",
                        to="callrouting.routingrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Request",
                "verbose_name_plural": "Routing Requests",
                "db_table": "callrouting_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutingWhatsAppMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_phone", models.CharField(db_index=True, max_length=15)),
                ("template_name", models.CharField(max_length=150)),
                (
                    "template_language",
                    models.CharField(blank=True, default="en", max_length=20),
                ),
                ("template_payload", models.JSONField(blank=True, default=dict)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                (
                    "doubletick_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_whatsapp_message",
                        to="doubletick.doubletickmessage",
                    ),
                ),
                (
                    "routing_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="callrouting.routingrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing WhatsApp Message",
                "verbose_name_plural": "Routing WhatsApp Messages",
                "db_table": "callrouting_whatsapp_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("phone_validated", "Phone Validated"),
                            ("invalid_phone", "Invalid Phone"),
                            ("rule_matched", "Rule Matched"),
                            ("no_rule", "No Rule"),
                            ("source_spa_open", "Source Spa Open"),
                            ("source_spa_closed", "Source Spa Closed"),
                            ("cooldown_blocked", "Cooldown Blocked"),
                            ("candidates_found", "Candidates Found"),
                            ("candidate_selected", "Candidate Selected"),
                            ("no_candidate", "No Candidate"),
                            ("whatsapp_queued", "WhatsApp Queued"),
                            ("whatsapp_sent", "WhatsApp Sent"),
                            ("whatsapp_delivered", "WhatsApp Delivered"),
                            ("whatsapp_read", "WhatsApp Read"),
                            ("whatsapp_failed", "WhatsApp Failed"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "routing_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="callrouting.routingrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Event",
                "verbose_name_plural": "Routing Events",
                "db_table": "callrouting_events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["routing_request", "created_at"],
                        name="cr_event_request_created_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="cr_event_type_created_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutingCandidate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "relevance_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_open", models.BooleanField(db_index=True, default=False)),
                ("is_eligible", models.BooleanField(db_index=True, default=False)),
                ("is_selected", models.BooleanField(db_index=True, default=False)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_candidates",
                        to="branches.branch",
                    ),
                ),
                (
                    "routing_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="callrouting.routingrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Candidate",
                "verbose_name_plural": "Routing Candidates",
                "db_table": "callrouting_candidates",
                "ordering": [
                    "routing_request",
                    "rank",
                    "-relevance_score",
                    "branch__spa_name",
                ],
                "indexes": [
                    models.Index(
                        fields=["routing_request", "is_selected"],
                        name="cr_cand_request_selected_idx",
                    ),
                    models.Index(
                        fields=["branch", "is_selected"],
                        name="cr_cand_branch_selected_idx",
                    ),
                    models.Index(
                        fields=["is_eligible", "is_open"],
                        name="cr_cand_eligible_open_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("routing_request", "branch"),
                        name="unique_callrouting_candidate_branch",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutingAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "routing_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="callrouting.routingrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Attempt",
                "verbose_name_plural": "Routing Attempts",
                "db_table": "callrouting_attempts",
                "ordering": ["routing_request", "-attempt_number"],
                "indexes": [
                    models.Index(
                        fields=["routing_request", "status"],
                        name="cr_attempt_request_status_idx",
                    ),
                    models.Index(fields=["started_at"], name="cr_attempt_started_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("routing_request", "attempt_number"),
                        name="unique_callrouting_attempt_number",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="routingrequest",
            index=models.Index(
                fields=["status", "created_at"], name="cr_req_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routingrequest",
            index=models.Index(
                fields=["routing_type", "status"], name="cr_req_type_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routingrequest",
            index=models.Index(
                fields=["source_branch", "created_at"], name="cr_req_branch_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routingrequest",
            index=models.Index(
                fields=["routing_rule", "created_at"], name="cr_req_rule_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routingrequest",
            index=models.Index(
                fields=["normalized_phone", "created_at"],
                name="cr_req_phone_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="routingrequest",
            index=models.Index(fields=["call_time"], name="cr_req_call_time_idx"),
        ),
        migrations.AddIndex(
            model_name="routingwhatsappmessage",
            index=models.Index(
                fields=["status", "created_at"], name="cr_wa_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routingwhatsappmessage",
            index=models.Index(
                fields=["provider_message_id"], name="cr_wa_provider_msg_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routingwhatsappmessage",
            index=models.Index(
                fields=["recipient_phone", "created_at"],
                name="cr_wa_recipient_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingwhatsappmessage",
            constraint=models.UniqueConstraint(
                fields=("routing_request",), name="unique_callrouting_whatsapp_request"
            ),
        ),
    ]
