# Generated by Django 5.2.16 on 2026-08-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callrouting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routingwhatsappmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
