"""
Django settings for calllog_system project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Initialize Environ
env = environ.Env()
# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-default-key-change-in-prod")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=['*'])

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=True)
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])

CORS_ALLOW_HEADERS = ["*"]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    # Third-party apps
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    "drf_spectacular",


    # Local apps
    "core",
    "apps.accounts",
    "apps.branches",
    "apps.devices",
    "apps.calllogs",
    "apps.common",
    "apps.monitoring",
    "apps.analytics",
    "apps.exports",
    "apps.dashboard",
    "apps.contacts",
    "apps.leadmanagement",
    "apps.notifications",
    "apps.doubletick",
    "apps.bots",
    "apps.locations",
]



MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Custom User Model
AUTH_USER_MODEL = "accounts.User"

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 30,
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "EXCEPTION_HANDLER": "apps.common.exceptions.custom_exception_handler",
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
}

# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="CallLog System <noreply@calllogsystem.com>")

# Hilite Multimedia SMS gateway for phone OTP login.
SMS_API_URL = env("SMS_API_URL", default="")
SMS_USERNAME = env("SMS_USERNAME", default="")
SMS_API_KEY = env("SMS_API_KEY", default="")
SMS_API_REQUEST = env("SMS_API_REQUEST", default="Text")
SMS_ROUTE = env("SMS_ROUTE", default="ServiceImplicit")
SMS_SENDER_ID = env("SMS_SENDER_ID", default="")
SMS_TEMPLATE_ID = env("SMS_TEMPLATE_ID", default="")
SMS_MOBILE_COUNTRY_CODE = env("SMS_MOBILE_COUNTRY_CODE", default="")
SMS_VERIFY_SSL = env.bool("SMS_VERIFY_SSL", default=True)
SKIP_SMS = env.bool("SKIP_SMS", default=False)
SMS_OTP_MESSAGE_TEMPLATE = env(
    "SMS_OTP_MESSAGE_TEMPLATE",
    default="Dear Customer, your Code for login to Spa Advisor is {otp}. This Code is valid for 5 minutes. Do not share this OTP with anyone. Thank You",
)

# Dotted path to the approved SMS sender used for phone OTP login.
# Example signature: sender(phone_number=..., otp=..., user=...)
PHONE_OTP_SENDER = env("PHONE_OTP_SENDER", default="apps.accounts.services.sms_sender.send_phone_otp")

# Celery Configuration
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://localhost:6379/1")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
MONITORING_OFFLINE_AFTER_MINUTES = env.int("MONITORING_OFFLINE_AFTER_MINUTES", default=20)
MONITORING_LOW_BATTERY_PERCENT = env.int("MONITORING_LOW_BATTERY_PERCENT", default=15)
MONITORING_BATTERY_RECOVERY_PERCENT = env.int("MONITORING_BATTERY_RECOVERY_PERCENT", default=20)
MONITORING_WEAK_SIGNAL_DBM = env.int("MONITORING_WEAK_SIGNAL_DBM", default=-105)
MONITORING_SIGNAL_RECOVERY_DBM = env.int("MONITORING_SIGNAL_RECOVERY_DBM", default=-95)
MONITORING_STORAGE_ALERT_MB = env.float("MONITORING_STORAGE_ALERT_MB", default=1024.0)

CELERY_BEAT_SCHEDULE = {
    'check-offline-devices-every-5-mins': {
        'task': 'apps.monitoring.tasks.check_offline_devices',
        'schedule': 300.0,  # 5 minutes
    },
    'check-sync-health-every-15-mins': {
        'task': 'apps.monitoring.tasks.check_device_sync_health',
        'schedule': 900.0,  # 15 minutes
    },
    'send-due-missed-call-reminders-every-5-mins': {
        'task': 'apps.calllogs.tasks.send_due_missed_call_reminders',
        'schedule': 300.0,  # 5 minutes
    },
}

# Caching (Redis)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_CACHE_URL", default="redis://127.0.0.1:6379/2"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        }
    }
}

# CHANNEL_LAYERS Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [env("REDIS_URL", default="redis://localhost:6379/3")],
        },
    },
}

# Firebase Configuration
_firebase_path = env("FIREBASE_SERVICE_ACCOUNT_KEY", default="firebase/firebase-credentials.json")
if not os.path.isabs(_firebase_path):
    FIREBASE_SERVICE_ACCOUNT_KEY = str(BASE_DIR / _firebase_path)
else:
    FIREBASE_SERVICE_ACCOUNT_KEY = _firebase_path

# DoubleTick WhatsApp lead integration. The webhook secret is required for
# accepting incoming provider callbacks; the API key/base URL are reserved for
# future outbound DoubleTick API calls.
DOUBLETICK_WEBHOOK_SECRET = env("DOUBLETICK_WEBHOOK_SECRET", default="")
DOUBLETICK_API_KEY = env("DOUBLETICK_API_KEY", default="")
DOUBLETICK_BASE_URL = env("DOUBLETICK_BASE_URL", default="https://public.doubletick.io")
DOUBLETICK_SEND_TEXT_ENDPOINT = env("DOUBLETICK_SEND_TEXT_ENDPOINT", default="/whatsapp/message/text")
DOUBLETICK_AUTH_HEADER = env("DOUBLETICK_AUTH_HEADER", default="Authorization")
DOUBLETICK_AUTH_SCHEME = env("DOUBLETICK_AUTH_SCHEME", default="Bearer")
DOUBLETICK_SEND_FROM_WABA_NUMBER = env("DOUBLETICK_SEND_FROM_WABA_NUMBER", default="")
DOUBLETICK_PENDING_ATTENTION_MINUTES = env.int("DOUBLETICK_PENDING_ATTENTION_MINUTES", default=10)
DOUBLETICK_PENDING_ARCHIVE_DAYS = env.int("DOUBLETICK_PENDING_ARCHIVE_DAYS", default=30)
DOUBLETICK_LOCATION_REQUEST_MESSAGE = env(
    "DOUBLETICK_LOCATION_REQUEST_MESSAGE",
    default="Just Provide Me Your Location So That I Can Help You With Booking...\n\nबस मुझे अपना स्थान बताएं ताकि मैं बुकिंग में आपकी मदद कर सकूं..",
)

# Spectacular Settings for API Documentation
SPECTACULAR_SETTINGS = {
    "TITLE": "CallLog System API",
    "DESCRIPTION": "Comprehensive API documentation for the CallLog System. Managed call logs, branches, devices, and lead management.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": True,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/v1/",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "ENUM_NAME_OVERRIDES": {
        "CallTypeEnum": "apps.calllogs.models.CallLog.CallType",
        "NotificationTypeEnum": "apps.notifications.models.Notification.NotificationType",
    },
    "SECURITY": [
        {
            "jwtAuth": [],
        },
        {
            "DeviceAuth": [],
            "X-Device-Secret": [],
        }
    ],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            },
            "DeviceAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "X-Device-ID",
            },
            "X-Device-Secret": {
                "type": "apiKey",
                "in": "header",
                "name": "X-Device-Secret",
            }
        }
    },
}
