# Generated manually because the local Python runtime is unavailable in this workspace.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0004_alter_branch_spa_name"),
        ("devices", "0004_lastsynchistory"),
        ("doubletick", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoubleTickChannel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("waba_number", models.CharField(max_length=30, unique=True)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("branch_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="doubletick_channels", to="branches.branchgroups")),
            ],
            options={"db_table": "doubletick_channels", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="DoubleTickLeadArea",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("distribution_mode", models.CharField(choices=[("broadcast_claim", "Broadcast Claim"), ("round_robin", "Round Robin"), ("manual", "Manual")], default="broadcast_claim", max_length=30)),
                ("claim_timeout_minutes", models.PositiveIntegerField(default=30)),
                ("contact_start_timeout_minutes", models.PositiveIntegerField(default=10)),
                ("auto_release_enabled", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={"db_table": "doubletick_lead_areas", "ordering": ["city", "name"]},
        ),
        migrations.CreateModel(
            name="DoubleTickCustomer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dt_customer_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("normalized_phone", models.CharField(db_index=True, max_length=15)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("whatsapp_name", models.CharField(blank=True, max_length=255)),
                ("raw_profile", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customers", to="doubletick.doubletickchannel")),
            ],
            options={"db_table": "doubletick_customers", "ordering": ["-last_seen_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="DoubleTickAreaAlias",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(max_length=255)),
                ("normalized_alias", models.CharField(db_index=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_from_manual_mapping", models.BooleanField(default=False)),
                ("channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="area_aliases", to="doubletick.doubletickchannel")),
                ("lead_area", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="doubletick.doubletickleadarea")),
            ],
            options={"db_table": "doubletick_area_aliases"},
        ),
        migrations.CreateModel(
            name="DoubleTickLeadAreaBranch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("receives_leads", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="doubletick_area_mappings", to="branches.branch")),
                ("lead_area", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="branch_mappings", to="doubletick.doubletickleadarea")),
            ],
            options={"db_table": "doubletick_lead_area_branches", "ordering": ["priority", "branch__spa_name"], "unique_together": {("lead_area", "branch")}},
        ),
        migrations.CreateModel(
            name="DoubleTickConversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("new", "New"), ("pending", "Pending"), ("awaiting_customer", "Awaiting Customer"), ("awaiting_location", "Awaiting Location"), ("awaiting_service", "Awaiting Service"), ("manual_attention", "Manual Attention"), ("area_unmatched", "Area Unmatched"), ("qualified", "Qualified"), ("distributed", "Distributed"), ("resolved", "Resolved"), ("inactive", "Inactive"), ("spam", "Spam"), ("closed", "Closed")], db_index=True, default="new", max_length=30)),
                ("pending_reason", models.CharField(blank=True, choices=[("greeting_only", "Greeting Only"), ("incomplete_bot_flow", "Incomplete Bot Flow"), ("customer_stopped_replying", "Customer Stopped Replying"), ("missing_location", "Missing Location"), ("invalid_location", "Invalid Location"), ("unmatched_location", "Unmatched Location"), ("ambiguous_location", "Ambiguous Location"), ("manual_reply_required", "Manual Reply Required"), ("other", "Other")], db_index=True, max_length=40)),
                ("priority", models.IntegerField(default=0)),
                ("raw_city", models.CharField(blank=True, max_length=100)),
                ("raw_area", models.CharField(blank=True, max_length=100)),
                ("raw_service", models.CharField(blank=True, max_length=255)),
                ("first_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_customer_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_agent_message_at", models.DateTimeField(blank=True, null=True)),
                ("customer_last_replied_at", models.DateTimeField(blank=True, null=True)),
                ("team_last_replied_at", models.DateTimeField(blank=True, null=True)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("requires_manual_attention", models.BooleanField(db_index=True, default=False)),
                ("bot_completed", models.BooleanField(default=False)),
                ("area_confirmed", models.BooleanField(db_index=True, default=False)),
                ("dt_conversation_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("assigned_support_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="doubletick_support_conversations", to=settings.AUTH_USER_MODEL)),
                ("channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="doubletick.doubletickchannel")),
                ("current_lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="current_for_conversations", to="doubletick.doubleticklead")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="doubletick.doubletickcustomer")),
                ("matched_area", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="doubletick.doubletickleadarea")),
            ],
            options={"db_table": "doubletick_conversations", "ordering": ["-last_message_at", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="doubleticklead",
            name="status",
            field=models.CharField(choices=[("qualified", "Qualified"), ("area_matched", "Area Matched"), ("available", "Available"), ("claimed", "Claimed"), ("opened", "Opened"), ("contacting", "Contacting"), ("contacted", "Contacted"), ("follow_up", "Follow Up"), ("booked", "Booked"), ("not_interested", "Not Interested"), ("released", "Released"), ("expired", "Expired"), ("lost", "Lost"), ("closed", "Closed"), ("failed", "Failed"), ("new", "New"), ("assigned", "Assigned"), ("unassigned", "Unassigned")], db_index=True, default="qualified", max_length=30),
        ),
        migrations.AddField(model_name="doubleticklead", name="conversation", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leads", to="doubletick.doubletickconversation")),
        migrations.AddField(model_name="doubleticklead", name="customer", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leads", to="doubletick.doubletickcustomer")),
        migrations.AddField(model_name="doubleticklead", name="channel", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leads", to="doubletick.doubletickchannel")),
        migrations.AddField(model_name="doubleticklead", name="initial_message", field=models.TextField(blank=True)),
        migrations.AddField(model_name="doubleticklead", name="latest_customer_message", field=models.TextField(blank=True)),
        migrations.AddField(model_name="doubleticklead", name="message_type", field=models.CharField(blank=True, default="text", max_length=50)),
        migrations.AddField(model_name="doubleticklead", name="raw_city", field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name="doubleticklead", name="raw_area", field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name="doubleticklead", name="raw_service", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="doubleticklead", name="matched_area", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leads", to="doubletick.doubletickleadarea")),
        migrations.AddField(model_name="doubleticklead", name="dt_customer_id", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="doubleticklead", name="dt_first_message_id", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="doubleticklead", name="dt_last_message_id", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="doubleticklead", name="received_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="doubleticklead", name="qualified_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="doubleticklead", name="area_matched_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="doubleticklead", name="distributed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="doubleticklead", name="claimed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="doubleticklead", name="closed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="doubleticklead", name="current_branch", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="current_doubletick_leads", to="branches.branch")),
        migrations.AddField(model_name="doubleticklead", name="current_user", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="current_doubletick_leads", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="doubleticklead", name="current_device", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="current_doubletick_leads", to="devices.device")),
        migrations.AddField(model_name="doubleticklead", name="closed_reason", field=models.TextField(blank=True)),
        migrations.AddField(model_name="doubleticklead", name="remarks", field=models.TextField(blank=True)),
        migrations.CreateModel(
            name="DoubleTickMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dt_message_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("message_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("direction", models.CharField(choices=[("inbound", "Inbound"), ("outbound", "Outbound")], db_index=True, max_length=20)),
                ("origin", models.CharField(choices=[("customer", "Customer"), ("bot", "Bot"), ("agent", "Agent"), ("api", "API"), ("system", "System")], db_index=True, max_length=20)),
                ("message_type", models.CharField(default="text", max_length=50)),
                ("text", models.TextField(blank=True)),
                ("media_url", models.URLField(blank=True, null=True)),
                ("caption", models.TextField(blank=True, null=True)),
                ("interactive_payload", models.JSONField(blank=True, default=dict)),
                ("callback_data", models.TextField(blank=True, null=True)),
                ("status", models.CharField(choices=[("received", "Received"), ("queued", "Queued"), ("sent", "Sent"), ("delivered", "Delivered"), ("read", "Read"), ("failed", "Failed")], db_index=True, default="received", max_length=20)),
                ("customer_number", models.CharField(blank=True, max_length=30)),
                ("waba_number", models.CharField(blank=True, max_length=30)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="doubletick.doubletickconversation")),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="messages", to="doubletick.doubletickcustomer")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="messages", to="doubletick.doubleticklead")),
                ("sent_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="doubletick_sent_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "doubletick_messages", "ordering": ["received_at", "sent_at", "created_at"]},
        ),
        migrations.CreateModel(
            name="DoubleTickLeadVisibility",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("notification_error", models.TextField(blank=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="doubletick_visibilities", to="branches.branch")),
                ("device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="devices.device")),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="visibilities", to="doubletick.doubleticklead")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "doubletick_lead_visibilities"},
        ),
        migrations.CreateModel(
            name="DoubleTickLeadAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("claimed", "Claimed"), ("opened", "Opened"), ("contact_started", "Contact Started"), ("contacted", "Contacted"), ("follow_up", "Follow Up"), ("released", "Released"), ("expired", "Expired"), ("booked", "Booked"), ("lost", "Lost"), ("closed", "Closed")], db_index=True, default="claimed", max_length=30)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("contact_started_at", models.DateTimeField(blank=True, null=True)),
                ("contact_completed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                ("release_reason", models.TextField(blank=True)),
                ("assigned_device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="devices.device")),
                ("assigned_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="doubletick_assignments", to=settings.AUTH_USER_MODEL)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="doubletick_assignments", to="branches.branch")),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="doubletick.doubleticklead")),
            ],
            options={"db_table": "doubletick_lead_assignments", "ordering": ["-attempt_number"]},
        ),
        migrations.AddField(model_name="doubleticklead", name="active_assignment", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="active_for_leads", to="doubletick.doubletickleadassignment")),
        migrations.CreateModel(
            name="DoubleTickActivity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("webhook_received", "Webhook Received"), ("conversation_created", "Conversation Created"), ("message_received", "Message Received"), ("message_sent", "Message Sent"), ("manual_reply_sent", "Manual Reply Sent"), ("customer_replied", "Customer Replied"), ("pending_reason_updated", "Pending Reason Updated"), ("manual_attention_required", "Manual Attention Required"), ("location_requested", "Location Requested"), ("location_received", "Location Received"), ("area_matched", "Area Matched"), ("area_unmatched", "Area Unmatched"), ("lead_qualified", "Lead Qualified"), ("lead_distributed", "Lead Distributed"), ("notification_sent", "Notification Sent"), ("viewed", "Viewed"), ("claimed", "Claimed"), ("contact_started", "Contact Started"), ("status_updated", "Status Updated"), ("follow_up_added", "Follow Up Added"), ("released", "Released"), ("reassigned", "Reassigned"), ("booked", "Booked"), ("lost", "Lost"), ("closed", "Closed"), ("processing_failed", "Processing Failed")], db_index=True, max_length=50)),
                ("old_status", models.CharField(blank=True, max_length=50)),
                ("new_status", models.CharField(blank=True, max_length=50)),
                ("note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assignment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="timeline", to="doubletick.doubletickleadassignment")),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="branches.branch")),
                ("conversation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="timeline", to="doubletick.doubletickconversation")),
                ("device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="devices.device")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="timeline", to="doubletick.doubleticklead")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "doubletick_activities", "ordering": ["-created_at"]},
        ),
        migrations.AddField(model_name="doubletickwebhooklog", name="conversation", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="webhook_logs", to="doubletick.doubletickconversation")),
        migrations.AddField(model_name="doubletickwebhooklog", name="message", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="webhook_logs", to="doubletick.doubletickmessage")),
        migrations.AddConstraint(
            model_name="doubletickleadassignment",
            constraint=models.UniqueConstraint(fields=("lead",), condition=models.Q(is_active=True), name="unique_active_doubletick_assignment"),
        ),
    ]
