# Generated by Django 4.2.28 on 2026-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doubletick", "0002_conversations_area_distribution"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="doubletickactivity",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="dt_activity_conv_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickactivity",
            index=models.Index(
                fields=["lead", "created_at"], name="dt_activity_lead_created_idx2"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickactivity",
            index=models.Index(fields=["action"], name="dt_activity_action_idx2"),
        ),
        migrations.AddIndex(
            model_name="doubletickareaalias",
            index=models.Index(
                fields=["normalized_alias", "is_active"],
                name="dt_alias_norm_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickconversation",
            index=models.Index(
                fields=["status", "pending_reason"], name="dt_conv_status_reason_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickconversation",
            index=models.Index(
                fields=["requires_manual_attention"], name="dt_conv_manual_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickconversation",
            index=models.Index(
                fields=["dt_conversation_id"], name="dt_conv_provider_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickconversation",
            index=models.Index(fields=["last_message_at"], name="dt_conv_last_msg_idx"),
        ),
        migrations.AddIndex(
            model_name="doubletickcustomer",
            index=models.Index(fields=["dt_customer_id"], name="dt_customer_id_idx"),
        ),
        migrations.AddIndex(
            model_name="doubletickcustomer",
            index=models.Index(
                fields=["normalized_phone"], name="dt_customer_phone_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubleticklead",
            index=models.Index(
                fields=["current_branch"], name="dt_lead_current_branch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubleticklead",
            index=models.Index(
                fields=["current_user"], name="dt_lead_current_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubleticklead",
            index=models.Index(
                fields=["matched_area", "status"], name="dt_lead_area_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickleadarea",
            index=models.Index(fields=["normalized_name"], name="dt_area_norm_idx"),
        ),
        migrations.AddIndex(
            model_name="doubletickleadarea",
            index=models.Index(
                fields=["city", "is_active"], name="dt_area_city_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickleadassignment",
            index=models.Index(
                fields=["lead", "is_active"], name="dt_assignment_lead_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickleadassignment",
            index=models.Index(
                fields=["assigned_user", "is_active"],
                name="dt_assignment_user_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickleadvisibility",
            index=models.Index(
                fields=["lead", "branch"], name="dt_visibility_lead_branch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickleadvisibility",
            index=models.Index(
                fields=["user", "is_visible"], name="dt_visibility_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickleadvisibility",
            index=models.Index(
                fields=["device", "is_visible"], name="dt_visibility_device_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickmessage",
            index=models.Index(
                fields=["conversation", "created_at"], name="dt_msg_conv_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubletickmessage",
            index=models.Index(fields=["dt_message_id"], name="dt_msg_dt_id_idx"),
        ),
        migrations.AddIndex(
            model_name="doubletickmessage",
            index=models.Index(fields=["message_id"], name="dt_msg_provider_id_idx"),
        ),
        migrations.AddIndex(
            model_name="doubletickmessage",
            index=models.Index(
                fields=["direction", "origin"], name="dt_msg_direction_origin_idx"
            ),
        ),
    ]
