# Generated by Django 4.2.28 on 2026-06-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doubletick", "0004_message_sender_metadata_team_mapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doubletickmessage",
            options={
                "ordering": [
                    "message_timestamp",
                    "received_at",
                    "sent_at",
                    "created_at",
                ]
            },
        ),
    ]
