# Generated by Django 4.2.27 on 2026-06-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doubletick", "0007_seed_doubletick_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doubletickwebhooklog",
            name="doubletick_event_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
