# Generated by Django 4.2.27 on 2026-06-23 07:39

from django.db import migrations, models
import django.db.models.deletion


def link_exact_location_areas(apps, schema_editor):
    DoubleTickLeadArea = apps.get_model("doubletick", "DoubleTickLeadArea")
    Area = apps.get_model("locations", "Area")

    for routing_profile in DoubleTickLeadArea.objects.filter(
        location_area__isnull=True,
        is_deleted=False,
    ).iterator():
        matches = Area.objects.filter(
            normalized_name=routing_profile.normalized_name,
            city__name__iexact=routing_profile.city,
            is_deleted=False,
        ).values_list("id", flat=True)[:2]
        match_ids = list(matches)
        if len(match_ids) == 1:
            routing_profile.location_area_id = match_ids[0]
            routing_profile.save(update_fields=["location_area"])


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("doubletick", "0008_alter_doubletickwebhooklog_doubletick_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="doubletickleadarea",
            name="location_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Master CRM area represented by this DoubleTick routing profile.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doubletick_routing_profiles",
                to="locations.area",
            ),
        ),
        migrations.RunPython(link_exact_location_areas, migrations.RunPython.noop),
    ]
