# Generated by Django 4.2.28 on 2026-03-20 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "spa_name",
                    models.CharField(
                        help_text="Full name of the Spa location.", max_length=255
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique short code identifying this branch (e.g. 'SPA-001').",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.PositiveIntegerField()),
                ("address", models.TextField()),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Branch contact phone number.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "db_table": "branches",
                "indexes": [
                    models.Index(fields=["code"], name="branches_code_95622b_idx"),
                    models.Index(
                        fields=["state", "city"], name="branches_state_5527f3_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="branches_is_acti_830392_idx"
                    ),
                ],
            },
        ),
    ]
