# Generated by Django 4.2.27 on 2026-03-26 10:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchGroups",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Branch Group",
                "verbose_name_plural": "Branch Groups",
                "db_table": "branch_groups",
            },
        ),
        migrations.AddField(
            model_name="branch",
            name="branch_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Each branch belongs to only one group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="branches.branchgroups",
            ),
        ),
    ]
