# Generated by Django 4.2.27 on 2026-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_branchgroups_branch_branch_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="code",
            field=models.CharField(
                help_text="Unique short code identifying this branch (e.g. 'SPA-001').",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="branchgroups",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="unique_code_if_not_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="branchgroups",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="unique_name_if_not_deleted",
            ),
        ),
    ]
