# Generated by Django 4.2.27 on 2026-04-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_alter_branch_code_alter_branchgroups_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="spa_name",
            field=models.CharField(
                db_index=True,
                help_text="Full name of the Spa location.",
                max_length=255,
            ),
        ),
    ]
