# Generated by Django 4.2.27 on 2026-06-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("branches", "0004_alter_branch_spa_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="location_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary area for this branch (FK). Maps to locations.Area.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="locations.area",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="location_city",
            field=models.ForeignKey(
                blank=True,
                help_text="Normalized city (FK). Maps to locations.City.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="locations.city",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="location_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Location group/zone for this branch (FK). Maps to locations.LocationGroup.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="locations.locationgroup",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="location_state",
            field=models.ForeignKey(
                blank=True,
                help_text="Normalized state (FK). Maps to locations.State.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="locations.state",
            ),
        ),
    ]
