# Generated by Django 5.2.16 on 2026-08-13 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0005_add_location_fk_fields_to_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchOperatingHours",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        db_index=True,
                    ),
                ),
                ("is_closed", models.BooleanField(db_index=True, default=False)),
                ("is_24_hours", models.BooleanField(default=False)),
                ("opens_at", models.TimeField(blank=True, null=True)),
                ("closes_at", models.TimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Kolkata",
                        help_text="IANA timezone used to evaluate these branch hours.",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch these weekly operating hours belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Operating Hours",
                "verbose_name_plural": "Branch Operating Hours",
                "db_table": "branch_operating_hours",
                "ordering": ["branch__spa_name", "weekday", "opens_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "weekday"], name="branch_hours_branch_day_idx"
                    ),
                    models.Index(
                        fields=["branch", "is_active"],
                        name="branch_hours_branch_active_idx",
                    ),
                    models.Index(
                        fields=["weekday", "is_active"],
                        name="branch_hours_day_active_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("is_deleted", False)),
                        fields=("branch", "weekday"),
                        name="unique_active_branch_hours_weekday",
                    )
                ],
            },
        ),
    ]
