# Generated by Django 5.2.16 on 2026-08-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0006_branchoperatinghours"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="shared_link",
            field=models.URLField(
                blank=True,
                help_text="Google Maps shared link for this branch.",
                null=True,
            ),
        ),
    ]
