# Generated by Django 4.2.28 on 2026-03-20 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reminder", "Reminder"),
                            ("alert", "Alert / Warning"),
                            ("system", "System Announcement"),
                            ("sync_issue", "Device Stopped Syncing"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "firebase_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        help_text="The device this notification was sent to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
