# Generated by Codex on 2026-05-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_area_branches"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="The device this notification was sent to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user this notification was sent to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="accounts.user",
            ),
        ),
    ]
