# Generated by Django 4.2.27 on 2026-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_user_nullable_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("reminder", "Reminder"),
                    ("alert", "Alert / Warning"),
                    ("system", "System Announcement"),
                    ("sync_issue", "Device Stopped Syncing"),
                    ("missed_call_followup", "Missed Call Follow-up"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
